files:
  - source: /locales/translations/en/**/*.json
    translation: /locales/translations/%locale%/**/%original_file_name%
    languages_mapping:
      locale:
        ar: ar
        zh-CN: zh-hans
        zh-TW: zh-hant
        da: da
        fr: fr
        ja: ja
        pt-PT: pt
        ru: ru
        es-ES: es
        en: en-GB-oxendict
